services:
  karakeep-app:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep-app
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - ${PWD}/karakeep/data:/data
    ports:
      - 1234:3000
    environment:
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - NEXTAUTH_SECRET=QGeSMVmBylLOO3vMHdU3WbdDU++EGwyP/RvhF00u0ODuXay1
      - MEILI_MASTER_KEY=yE9gXg7MesybplFKuyRR1Qc0LGgk7+a65la/hmf0LlaNB2z1
      - NEXTAUTH_URL=https://karakeep.gengsudev.my.id
      - DATA_DIR=/data
      - CRAWLER_STORE_SCREENSHOT=true
      - CRAWLER_FULL_PAGE_SCREENSHOT=true
      - CRAWLER_ENABLE_ADBLOCKER=true
      # - OP3NA1NK3Y=

  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=yE9gXg7MesybplFKuyRR1Qc0LGgk7+a65la/hmf0LlaNB2z1
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ${PWD}/karakeep/meilisearch:/meili_data
