services:
  karakeep-app:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep-app
    restart: unless-stopped
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - ${PWD}/karakeep/data:/data
    ports:
      - 1234:3000
    environment:
      - MEILI_ADDR=http://karakeep-meilisearch:7700
      - BROWSER_WEB_URL=http://karakeep-chrome:9222
      - NEXTAUTH_SECRET=QGeSMVmBylLOO3vMHdU3WbdDU++EGwyP/RvhF00u0ODuXay1
      - MEILI_MASTER_KEY=yE9gXg7MesybplFKuyRR1Qc0LGgk7+a65la/hmf0LlaNB2z1
      - NEXTAUTH_URL=https://karakeep.gengsulab.my.id
      - DATA_DIR=/data
      - CRAWLER_STORE_SCREENSHOT=true
      - CRAWLER_FULL_PAGE_SCREENSHOT=true
      - CRAWLER_ENABLE_ADBLOCKER=true
      - OPENAI_BASE_URL=https://generativelanguage.googleapis.com/v1beta
      - OPENAI_API_KEY=YOUR_API_KEY=AIzaSyCeQDfuDMKd8wPk04DozcuIxSY6RccqRZs
      - INFERENCE_TEXT_MODEL=gemini-2.0-flash
      - INFERENCE_IMAGE_MODEL=gemini-2.0-flash
      - INFERENCE_ENABLE_AUTO_TAGGING=true
      - INFERENCE_ENABLE_AUTO_SUMMARIZATION=true
    networks:
      - universe
      # - OP3NA1NK3Y=

  karakeep-chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - universe

  karakeep-meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: karakeep-meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=yE9gXg7MesybplFKuyRR1Qc0LGgk7+a65la/hmf0LlaNB2z1
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ${PWD}/karakeep/meilisearch:/meili_data
    networks:
      - universe

networks:
  universe:
    external: true
